### ISSUE TITLE
Text area resizing issue at lower screen resolutions.

### ISSUE THREAD

**Issue by omnicons** [easymac/lounge-neuron#4]
The problem seems to be that it always resets the window to the default height, and then briefly scrolls it to bring the bottommost line of the text input box into the window... but it scrolls not just the text input box, but the entire chat window

> 18:03 Zuthal  Okay, there is a problem with the theme, at least in Chrome at my screen resolution, that makes it unusable
> 18:03 Dusk  What is it?
> 18:03 Zuthal  The chat window vibrates up and down if I type with at least three lines of text in the input box
> 18:04 Dusk  What
> 18:04 Zuthal  the more lines, the larger the amplitude of the vibration
> 18:04 Zuthal  Yes, that was my reaction too!
> 18:05 Zuthal  The problem seems to be that it always resets the window to the default height, and then briefly scrolls it to bring the bottommost line of the text input box into the window... but it scrolls not just the text input box, but the entire chat window
> 18:05 Zuthal  but not the channel list
> 18:12 Dusk  I'll need to know your screen resolution to test but yea
> 18:12 Dusk  If you can get me that that would be awesome
> 18:12 Zuthal  1280x800
> 18:13 Zuthal  on Chrome 52.0.2743.116, in maximised window (but not fullscreen)

**Comment by omnicons** [comment]
The problem also happens in fullscreen, so it doesn't appear to be a height issue.

**Comment by easymac** [comment]
... That's fascinating. I'm able to replicate this; I'll investigate further.

On iOS Safari (at iPhone 5s resolution), there's a problem where, as you type when you reach the 2nd line of text, the entire interface disappears until you backspace or submit (including the chat box)... but as soon as you reach the 3rd line of text, everything acts as expected.

I'm sure that these are related.

The input bar changed some between 2.0.0-pre.1 and 2.0.0-pre.6 -- I'm guessing this is a result of those modifications.

I'm going to first see if I can reproduce this in the default theme and then I will try to fix it (which will be easy provided it was a CSS problem to begin with).

Thanks for bringing this to my attention!

**Comment by easymac** [comment]
Yeah, that's **definitely** not happening on the vanilla theme, so I should be able to fix it with Neuron.

**Comment by omnicons** [comment]
You're welcome! I've got like 20 people using your theme so I'm sure I'll be bringing stuff to your attention or submitting my own PRs if I find stuff.

**Comment by easymac** [comment]
Hey! I've got it!

It was another easy one line fix. A near parent of the input bar had a fixed height that was throwing things off.

I've pushed changes to master; let me know if they work for you or if you're having more problems.

**Comment by omnicons** [comment]
Works in testing!

**Comment by easymac** [comment]
Yaaaaay!

Thanks again for your help. Let me know when something else goes wrong ;)
